### ISSUE TITLE
Error in external monitor SplatNet3 Monitor

### ISSUE THREAD

**Issue by JoshiBaker** [samuelthomas2774/nxapi#122]
Whenever I start Splatoon 3 I get this error:

```
Error: [znc] Membership required error.
    from https://api-lp1.znc.srv.nintendo.net/v2/Game/GetWebServiceToken (200 OK)
      { status: 9450,
        errorMessage: 'Membership required error.',
        correlationId: '471721f7-da65-42d1-b321-f011fbf4f4b0-735aaafa' }
    at CoralApi.fetch (file:///C:/Users/Joshi/AppData/Local/Programs/nxapi-app/resources/app/dist/bundle/chunk-users.js:8322:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async CoralApi.getWebServiceToken (file:///C:/Users/Joshi/AppData/Local/Programs/nxapi-app/resources/app/dist/bundle/chunk-users.js:8428:20)
    at async SplatNet3Api.loginWithCoral (file:///C:/Users/Joshi/AppData/Local/Programs/nxapi-app/resources/app/dist/bundle/chunk-users.js:97539:33)
    at async getBulletToken (file:///C:/Users/Joshi/AppData/Local/Programs/nxapi-app/resources/app/dist/bundle/chunk-users.js:97674:31)
    at async SplatNet3Monitor.init (file:///C:/Users/Joshi/AppData/Local/Programs/nxapi-app/resources/app/dist/bundle/chunk-users.js:97919:40)
    at async SplatNet3Monitor.loopRun (file:///C:/Users/Joshi/AppData/Local/Programs/nxapi-app/resources/app/dist/bundle/chunk-users.js:97752:35)
    at async SplatNet3Monitor.loop (file:///C:/Users/Joshi/AppData/Local/Programs/nxapi-app/resources/app/dist/bundle/chunk-users.js:97765:28)
    at async SplatNet3Monitor._run (file:///C:/Users/Joshi/AppData/Local/Programs/nxapi-app/resources/app/dist/bundle/chunk-users.js:97822:28)
```

**Comment by catgirlinspace** [comment]
Does your second account have Nintendo Switch Online and access to SplatNet 3?

**Comment by JoshiBaker** [comment]
I don't think so, I believe it's just a Nintendo Online account.

**Comment by hfcRed** [comment]
The account needs an online membership in order for this to work

**Comment by JoshiBaker** [comment]
Ahh gotcha, thank you
