### ISSUE TITLE
mac, errors when i had users added so i reinstalled it, and no longer can add users

### ISSUE THREAD

**Issue by Midnights-Crow** [samuelthomas2774/nxapi#136]
Error: [znca-api] Non-200 status code
from https://nxapi-znca-api.fancy.org.uk/api/znca/f (530 )
'<!DOCTYPE html>\n\n<!--[if I'... 6115 more characters
at genf (file:///Applications/Nintendo%20Switch%20Online.app/Contents/Resources/app/dist/bundle/chunk-users.js:8132:15)
at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
at async ZncaApiNxapi.genf (file:///Applications/Nintendo%20Switch%20Online.app/Contents/Resources/app/dist/bundle/chunk-users.js:8150:24)
at async CoralApi.loginWithSessionToken (file:///Applications/Nintendo%20Switch%20Online.app/Contents/Resources/app/dist/bundle/chunk-users.js:8496:23)
at async CoralApi.createWithSessionToken (file:///Applications/Nintendo%20Switch%20Online.app/Contents/Resources/app/dist/bundle/chunk-users.js:8481:22)
at async getToken (file:///Applications/Nintendo%20Switch%20Online.app/Contents/Resources/app/dist/bundle/chunk-users.js:8955:13)
at async addNsoAccount (file:///Applications/Nintendo%20Switch%20Online.app/Contents/Resources/app/dist/bundle/app-main-bundle.js:564:31)
at async askAddNsoAccount (file:///Applications/Nintendo%20Switch%20Online.app/Contents/Resources/app/dist/bundle/app-main-bundle.js:581:16)

**Comment by Nysonaisafox** [comment]
Same issue on linux: the app stopped loading data on all users, and after wiping the computer of all traces of the app and reinstalling it, it refuses to even add users
![image](https://github.com/user-attachments/assets/8805aab2-2b8d-4a02-b1e8-bd9705b2c755)

**Comment by FourHawk** [comment]
Please see [#134](https://github.com/samuelthomas2774/nxapi/issues/134) for some info about this

**Comment by samuelthomas2774** [comment]
Duplicate of #134, #135.
