### ISSUE TITLE
Error in authentication: 'The provided session_token_code is invalid'

### ISSUE THREAD

**Issue by preon7** [samuelthomas2774/nxapi#60]
Error encountered when authorizing with the Nintendo Account link.
Example error response:

> ```
> ErrorResponse: [na] Non-200 status code
>     from https://accounts.nintendo.com/connect/1.0.0/api/session_token (400 Bad Request)
>       { error: 'invalid_request',
>         error_description: 'The provided session_token_code is invalid' }
>     at getNintendoAccountSessionToken (file:///Users/ruiheng/Documents/splatoon/obs-splat/node_modules/nxapi/dist/api/na.js:25:15)
>     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
>     at async Object.handler (file:///Users/ruiheng/Documents/splatoon/obs-splat/node_modules/nxapi/dist/cli/nso/auth.js:56:19) {
>   response: Response {
>     size: 0,
>     [Symbol(Body internals)]: {
>       body: [PassThrough],
>       stream: [PassThrough],
>       boundary: null,
>       disturbed: true,
>       error: null
>     },
>     [Symbol(Response internals)]: {
>       type: 'default',
>       url: 'https://accounts.nintendo.com/connect/1.0.0/api/session_token',
>       status: 400,
>       statusText: 'Bad Request',
>       headers: [Object],
>       counter: 0,
>       highWaterMark: 16384
>     }
>   },
>   data: {
>     error: 'invalid_request',
>     error_description: 'The provided session_token_code is invalid'
>   },
>   body: '{"error":"invalid_request","error_description":"The provided session_token_code is invalid"}'
> }

Solution: replace the app version in [na.ts](https://github.com/samuelthomas2774/nxapi/blob/main/src/api/na.ts#L18) with the latest version (2.5.0 on Apr. 21 2023)

**Comment by preon7** [comment]
update: This solution only works on some user. Others still get the same error.

**Comment by preon7** [comment]
update: This solution only works on some user. Others still get the same error.
