### ISSUE TITLE
502 Bad Gateway

### ISSUE THREAD

**Issue by swindlesmccoop** [samuelthomas2774/nxapi#77]
I assume problems with the server but not sure. I was getting API ratelimit errors earlier as well.
```
[Window Title]
nxapi-app

[Main Instruction]
Error restoring monitor for user 9aadc07eb1080ef9

[Content]
Error: [znca-api] Non-200 status code
    from https://nxapi-znca-api.fancy.org.uk/api/znca/f (502 Bad Gateway)
      '<!DOCTYPE html>\n<!--[if lt IE 7]> <html class="no-js ie6 oldie" lang="en-US"> <![endif]-->\n<!--[if I'... 6304 more characters
    at genf (file:///C:/Users/Swindles/AppData/Local/Programs/nxapi-app/resources/app/dist/bundle/chunk-users.js:8132:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async ZncaApiNxapi.genf (file:///C:/Users/Swindles/AppData/Local/Programs/nxapi-app/resources/app/dist/bundle/chunk-users.js:8150:24)
    at async CoralApi.loginWithSessionToken (file:///C:/Users/Swindles/AppData/Local/Programs/nxapi-app/resources/app/dist/bundle/chunk-users.js:8496:23)
    at async CoralApi.createWithSessionToken (file:///C:/Users/Swindles/AppData/Local/Programs/nxapi-app/resources/app/dist/bundle/chunk-users.js:8481:22)
    at async getToken (file:///C:/Users/Swindles/AppData/Local/Programs/nxapi-app/resources/app/dist/bundle/chunk-users.js:8955:13)
    at async file:///C:/Users/Swindles/AppData/Local/Programs/nxapi-app/resources/app/dist/bundle/chunk-users.js:102283:35
    at async PresenceMonitorManager.start (file:///C:/Users/Swindles/AppData/Local/Programs/nxapi-app/resources/app/dist/bundle/app-main-bundle.js:1026:22)
    at async Store.restoreUserMonitorState (file:///C:/Users/Swindles/AppData/Local/Programs/nxapi-app/resources/app/dist/bundle/app-main-bundle.js:2243:13)
```

**Comment by swindlesmccoop** [comment]
Guess it just resolved itself
